@echo off
echo Stopping containers...
docker stop $(docker ps -q --filter "ancestor=fruit-api-h2") 2>nul

echo Building application...
mvn clean package -DskipTests

echo Building Docker image...
docker build -t fruit-api-h2 .

echo Starting container...
docker run -p 9000:9000 fruit-api-h2